[package]
name = "netlink-packet-xfrm"
version = "0.4.0"
authors = ["Scott Zuk <zooknotic@proton.me>"]
edition = "2021"
homepage = "https://github.com/rust-netlink/netlink-packet-xfrm"
repository = "https://github.com/rust-netlink/netlink-packet-xfrm"
keywords = ["netlink", "linux", "ipsec", "xfrm"]
license = "MIT"
readme = "README.md"
description = "netlink xfrm packet types for IPsec"

[dependencies]
libc= "0.2.177"
netlink-packet-core = { version = "0.9.0" }
zerocopy = { version = "0.8", features = ["derive"] }

[dev-dependencies]
lazy_static = "1.5.0"
netlink-proto = { version = "0.13" }
netlink-sys = { version = "0.9" }
