[package]
name = "netlink-packet-xfrm"
version = "0.3.1"
authors = ["Scott Zuk <zooknotic@proton.me>"]
edition = "2021"
homepage = "https://github.com/rust-netlink/netlink-packet-xfrm"
repository = "https://github.com/rust-netlink/netlink-packet-xfrm"
keywords = ["netlink", "linux", "ipsec", "xfrm"]
license = "MIT"
readme = "README.md"
description = "netlink xfrm packet types for IPsec"

[dependencies]
libc= "0.2.177"
netlink-packet-core = { version = "0.8.1" }

[dev-dependencies]
lazy_static = "1.5.0"
netlink-proto = { version = "0.12" }
netlink-sys = { version = "0.8.7" }
